
export const SAVE_FACEBOOK_PROFILE = 'SAVE_FACEBOOK_PROFILE'
export const GET_FACEBOOK_PROFILE = 'GET_FACEBOOK_PROFILE'

export const SAVE_GOOGLE_PROFILE = 'SAVE_GOOGLE_PROFILE'
export const GET_GOOGLE_PROFILE = 'GET_GOOGLE_PROFILE'
